<center> <img src = https://raw.githubusercontent.com/AndreyRysistov/DatasetsForPandas/main/hh%20label.jpg alt="drawing" style="width:400px;">

# <center> Проект: Анализ резюме из HeadHunter

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

# Исследование структуры данных

1. Прочитайте данные с помощью библиотеки Pandas. Совет: перед чтением обратите внимание на разделитель внутри файла.

In [6]:
#ваш код здесь
df = pd.read_csv('dst-3.0_16_1_hh_database.csv', sep=';')

2. Выведите несколько первых (последних) строк таблицы, чтобы убедиться в том, что ваши данные не повреждены. Ознакомьтесь с признаками и их структурой.

In [19]:
#ваш код здесь
print(df.head())
#print(df.tail())

                                   Пол, возраст           ЗП  \
0    Мужчина ,  39 лет , родился 27 ноября 1979   29000 руб.
1     Мужчина ,  60 лет , родился 20 марта 1959   40000 руб.
2  Женщина ,  36 лет , родилась 12 августа 1982   20000 руб.
3      Мужчина ,  38 лет , родился 25 июня 1980  100000 руб.
4     Женщина ,  26 лет , родилась 3 марта 1993  140000 руб.

                           Ищет работу на должность:  \
0                            Системный администратор
1                               Технический писатель
2                                           Оператор
3  Веб-разработчик (HTML / CSS / JS / PHP / базы ...
4                  Региональный менеджер по продажам

                        Город, переезд, командировки  \
0  Советск (Калининградская область) , не готов к...
1  Королев , не готов к переезду , готов к редким...
2  Тверь , не готова к переезду , не готова к ком...
3  Саратов , не готов к переезду , готов к редким...
4  Москва , не готова к переезду , готова к коман...

                                           Занятость  \
0  частичная занятость, проектная работа, полная ...
1  частичная занятость, проектная работа, полная ...
2                                   полная занятость
3  частичная занятость, проектная работа, полная ...
4                                   полная занятость

                                              График  \
0  гибкий график, полный день, сменный график, ва...
1  гибкий график, полный день, сменный график, уд...
2                                        полный день
3                    гибкий график, удаленная работа
4                                        полный день

                                         Опыт работы  \
0  Опыт работы 16 лет 10 месяцев  Август 2010 — п...
1  Опыт работы 19 лет 5 месяцев  Январь 2000 — по...
2  Опыт работы 10 лет 3 месяца  Октябрь 2004 — Де...
3  Опыт работы 18 лет 9 месяцев  Август 2017 — Ап...
4  Опыт работы 5 лет 7 месяцев  Региональный мене...

  Последнее/нынешнее место работы  \
0         МАОУ "СОШ № 1 г.Немана"
1    Временный трудовой коллектив
2                    ПАО Сбербанк
3                        OpenSoft
4                        Мармелад

                       Последняя/нынешняя должность  \
0                           Системный администратор
1  Менеджер проекта, Аналитик, Технический писатель
2                               Кассир-операционист
3                               Инженер-программист
4                              Менеджер по продажам

                                   Образование и ВУЗ Обновление резюме  \
0  Неоконченное высшее образование 2000  Балтийск...  16.04.2019 15:59
1  Высшее образование 1981  Военно-космическая ак...  12.04.2019 08:42
2  Среднее специальное образование 2002 Профессио...  16.04.2019 08:35
3  Высшее образование 2002  Саратовский государст...  08.04.2019 14:23
4  Высшее образование 2015 Кгу Психологии и педаг...  22.04.2019 10:32

                             Авто
0  Имеется собственный автомобиль
1                      Не указано
2                      Не указано
3                      Не указано
4                      Не указано

3. Выведите основную информацию о числе непустых значений в столбцах и их типах в таблице.

4. Обратите внимание на информацию о числе непустых значений.

In [20]:
#ваш код здесь
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44744 entries, 0 to 44743
Data columns (total 12 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Пол, возраст                     44744 non-null  object
 1   ЗП                               44744 non-null  object
 2   Ищет работу на должность:        44744 non-null  object
 3   Город, переезд, командировки     44744 non-null  object
 4   Занятость                        44744 non-null  object
 5   График                           44744 non-null  object
 6   Опыт работы                      44576 non-null  object
 7   Последнее/нынешнее место работы  44743 non-null  object
 8   Последняя/нынешняя должность     44742 non-null  object
 9   Образование и ВУЗ                44744 non-null  object
 10  Обновление резюме                44744 non-null  object
 11  Авто                             44744 non-null  object
dtypes: object(12)
memory usage: 4.1+ MB
None

5. Выведите основную статистическую информацию о столбцах.

In [21]:
#ваш код здесь
print(df.describe())

                                         Пол, возраст          ЗП  \
count                                           44744       44744
unique                                          16003         690
top     Мужчина ,  32 года , родился 17 сентября 1986  50000 руб.
freq                                               18        4064

       Ищет работу на должность:  \
count                      44744
unique                     14929
top      Системный администратор
freq                        3099

                             Город, переезд, командировки         Занятость  \
count                                               44744             44744
unique                                              10063                38
top     Москва , не готов к переезду , не готов к кома...  полная занятость
freq                                                 1261             30026

             График                                        Опыт работы  \
count         44744                                              44576
unique           47                                              44413
top     полный день  Опыт работы 10 лет 8 месяцев  Апрель 2018 — по...
freq          22727                                                  3

                          Последнее/нынешнее место работы  \
count                                               44743
unique                                              30214
top     Индивидуальное предпринимательство / частная п...
freq                                                  935

       Последняя/нынешняя должность  \
count                         44742
unique                        16927
top         Системный администратор
freq                           2062

                                        Образование и ВУЗ Обновление резюме  \
count                                               44744             44744
unique                                              40148             18838
top     Высшее образование 1987 Военный инженерный Кра...  07.05.2019 09:50
freq                                                    4                25

              Авто
count        44744
unique           2
top     Не указано
freq         32268

# Преобразование данных

1. Начнем с простого - с признака **"Образование и ВУЗ"**. Его текущий формат это: **<Уровень образования год выпуска ВУЗ специальность...>**. Например:
* Высшее образование 2016 Московский авиационный институт (национальный исследовательский университет)...
* Неоконченное высшее образование 2000  Балтийская государственная академия рыбопромыслового флота…
Нас будет интересовать только уровень образования.

Создайте с помощью функции-преобразования новый признак **"Образование"**, который должен иметь 4 категории: "высшее", "неоконченное высшее", "среднее специальное" и "среднее".

Выполните преобразование, ответьте на контрольные вопросы и удалите признак "Образование и ВУЗ".

Совет: обратите внимание на структуру текста в столбце **"Образование и ВУЗ"**. Гарантируется, что текущий уровень образования соискателя всегда находится в первых 2ух слов и начинается с заглавной буквы. Воспользуйтесь этим.

*Совет: проверяйте полученные категории, например, с помощью метода unique()*

In [22]:
#ваш код здесь
def extract_education(edu_string):
    level = " ".join(edu_string.split()[:2]).lower()  # Берем первые два слова и приводим к нижнему регистру
    
    if "высшее" in level:
        return "высшее"
    elif "неоконченное высшее" in level:
        return "неоконченное высшее"
    elif "среднее специальное" in level:
        return "среднее специальное"
    elif "среднее" in level:
        return "среднее"
    else:
        return None

# Создаем столбец "Образование"
df["Образование"] = df["Образование и ВУЗ"].apply(extract_education)

# проверяем какие уникальные категории получились
print(df["Образование"].unique())

# удаляем старый столбец
df.drop(columns=["Образование и ВУЗ"], inplace=True)

# Проверка
print(df.head())

['высшее' 'среднее специальное' 'среднее']
                                   Пол, возраст           ЗП  \
0    Мужчина ,  39 лет , родился 27 ноября 1979   29000 руб.
1     Мужчина ,  60 лет , родился 20 марта 1959   40000 руб.
2  Женщина ,  36 лет , родилась 12 августа 1982   20000 руб.
3      Мужчина ,  38 лет , родился 25 июня 1980  100000 руб.
4     Женщина ,  26 лет , родилась 3 марта 1993  140000 руб.

                           Ищет работу на должность:  \
0                            Системный администратор
1                               Технический писатель
2                                           Оператор
3  Веб-разработчик (HTML / CSS / JS / PHP / базы ...
4                  Региональный менеджер по продажам

                        Город, переезд, командировки  \
0  Советск (Калининградская область) , не готов к...
1  Королев , не готов к переезду , готов к редким...
2  Тверь , не готова к переезду , не готова к ком...
3  Саратов , не готов к переезду , готов к редким...
4  Москва , не готова к переезду , готова к коман...

                                           Занятость  \
0  частичная занятость, проектная работа, полная ...
1  частичная занятость, проектная работа, полная ...
2                                   полная занятость
3  частичная занятость, проектная работа, полная ...
4                                   полная занятость

                                              График  \
0  гибкий график, полный день, сменный график, ва...
1  гибкий график, полный день, сменный график, уд...
2                                        полный день
3                    гибкий график, удаленная работа
4                                        полный день

                                         Опыт работы  \
0  Опыт работы 16 лет 10 месяцев  Август 2010 — п...
1  Опыт работы 19 лет 5 месяцев  Январь 2000 — по...
2  Опыт работы 10 лет 3 месяца  Октябрь 2004 — Де...
3  Опыт работы 18 лет 9 месяцев  Август 2017 — Ап...
4  Опыт работы 5 лет 7 месяцев  Региональный мене...

  Последнее/нынешнее место работы  \
0         МАОУ "СОШ № 1 г.Немана"
1    Временный трудовой коллектив
2                    ПАО Сбербанк
3                        OpenSoft
4                        Мармелад

                       Последняя/нынешняя должность Обновление резюме  \
0                           Системный администратор  16.04.2019 15:59
1  Менеджер проекта, Аналитик, Технический писатель  12.04.2019 08:42
2                               Кассир-операционист  16.04.2019 08:35
3                               Инженер-программист  08.04.2019 14:23
4                              Менеджер по продажам  22.04.2019 10:32

                             Авто          Образование
0  Имеется собственный автомобиль               высшее
1                      Не указано               высшее
2                      Не указано  среднее специальное
3                      Не указано               высшее
4                      Не указано               высшее

2. Теперь нас интересует столбец **"Пол, возраст"**. Сейчас он представлен в формате **<Пол , возраст , дата рождения >**. Например:
* Мужчина , 39 лет , родился 27 ноября 1979 
* Женщина , 21 год , родилась 13 января 2000
Как вы понимаете, нам необходимо выделить каждый параметр в отдельный столбец.

Создайте два новых признака **"Пол"** и **"Возраст"**. При этом важно учесть:
* Признак пола должен иметь 2 уникальных строковых значения: 'М' - мужчина, 'Ж' - женщина. 
* Признак возраста должен быть представлен целыми числами.

Выполните преобразование, ответьте на контрольные вопросы и удалите признак **"Пол, возраст"** из таблицы.

*Совет: обратите внимание на структуру текста в столбце, в части на то, как разделены параметры пола, возраста и даты рождения между собой - символом ' , '. 
Гарантируется, что структура одинакова для всех строк в таблице. Вы можете воспользоваться этим.*

In [ ]:
#ваш код здесь
def extract_gender_age(value):
    parts = value.split(", ")
    gender = "М" if parts[0] == "Мужчина" else "Ж"
    age = int(parts[1].split(" ")[0])  # Берем первое слово из возраста и преобразуем в int
    return gender, age

# Применяем функцию к столбцу "Пол, возраст"
df[["Пол", "Возраст"]] = df["Пол, возраст"].apply(lambda x: pd.Series(extract_gender_age(x)))

# Удаляем старый столбец
df.drop(columns=["Пол, возраст"], inplace=True)

ValueError: invalid literal for int() with base 10: ''

3. Следующим этапом преобразуем признак **"Опыт работы"**. Его текущий формат - это: **<Опыт работы: n лет m месяцев, периоды работы в различных компаниях…>**. 

Из столбца нам необходимо выделить общий опыт работы соискателя в месяцах, новый признак назовем "Опыт работы (месяц)"

Для начала обсудим условия решения задачи:
* Во-первых, в данном признаке есть пропуски. Условимся, что если мы встречаем пропуск, оставляем его как есть (функция-преобразование возвращает NaN)
* Во-вторых, в данном признаке есть скрытые пропуски. Для некоторых соискателей в столбце стоит значения "Не указано". Их тоже обозначим как NaN (функция-преобразование возвращает NaN)
* В-третьих, нас не интересует информация, которая описывается после указания опыта работы (периоды работы в различных компаниях)
* В-четвертых, у нас есть проблема: опыт работы может быть представлен только в годах или только месяцах. Например, можно встретить следующие варианты:
    * Опыт работы 3 года 2 месяца…
    * Опыт работы 4 года…
    * Опыт работы 11 месяцев…
    * Учитывайте эту особенность в вашем коде

Учитывайте эту особенность в вашем коде

В результате преобразования у вас должен получиться столбец, содержащий информацию о том, сколько месяцев проработал соискатель.
Выполните преобразование, ответьте на контрольные вопросы и удалите столбец **"Опыт работы"** из таблицы.

In [2]:
#ваш код здесь  

import re
import numpy as np

def convert_experience_to_months(text):
    if pd.isnull(text) or text.strip() == "Не указано":
        return np.nan
    
    # Поиск количества лет и месяцев с помощью регулярных выражений
    years = re.search(r"(\d+)\s+год", text)
    months = re.search(r"(\d+)\s+месяц", text)

    total_months = 0

    if years:
        total_months += int(years.group(1)) * 12
    if months:
        total_months += int(months.group(1))
    
    return total_months

4. Хорошо идем! Следующий на очереди признак "Город, переезд, командировки". Информация в нем представлена в следующем виде: **<Город , (метро) , готовность к переезду (города для переезда) , готовность к командировкам>**. В скобках указаны необязательные параметры строки. Например, можно встретить следующие варианты:

* Москва , не готов к переезду , готов к командировкам
* Москва , м. Беломорская , не готов к переезду, не готов к командировкам
* Воронеж , готов к переезду (Сочи, Москва, Санкт-Петербург) , готов к командировкам

Создадим отдельные признаки **"Город"**, **"Готовность к переезду"**, **"Готовность к командировкам"**. При этом важно учесть:

* Признак **"Город"** должен содержать только 4 категории: "Москва", "Санкт-Петербург" и "город-миллионник" (их список ниже), остальные обозначьте как "другие".

    Список городов-миллионников:
    
   <code>million_cities = ['Новосибирск', 'Екатеринбург','Нижний Новгород','Казань', 'Челябинск','Омск', 'Самара', 'Ростов-на-Дону', 'Уфа', 'Красноярск', 'Пермь', 'Воронеж','Волгоград']
    </code>
    Инфорация о метро, рядом с которым проживает соискатель нас не интересует.
* Признак **"Готовность к переезду"** должен иметь два возможных варианта: True или False. Обратите внимание, что возможны несколько вариантов описания готовности к переезду в признаке "Город, переезд, командировки". Например:
    * … , готов к переезду , …
    * … , не готова к переезду , …
    * … , готова к переезду (Москва, Санкт-Петербург, Ростов-на-Дону)
    * … , хочу переехать (США) , …
    
    Нас интересует только сам факт возможности или желания переезда.
* Признак **"Готовность к командировкам"** должен иметь два возможных варианта: True или False. Обратите внимание, что возможны несколько вариантов описания готовности к командировкам в признаке "Город, переезд, командировки". Например:
    * … , готов к командировкам , … 
    * … , готова к редким командировкам , …
    * … , не готов к командировкам , …
    
    Нас интересует только сам факт готовности к командировке.
    
    Еще один важный факт: при выгрузки данных у некоторых соискателей "потерялась" информация о готовности к командировкам. Давайте по умолчанию будем считать, что такие соискатели не готовы к командировкам.
    
Выполните преобразования и удалите столбец **"Город, переезд, командировки"** из таблицы.

*Совет: обратите внимание на то, что структура текста может меняться в зависимости от указания ближайшего метро. Учите это, если будете использовать порядок слов в своей программе.*

In [3]:
#ваш код здесь
million_cities = ['Новосибирск', 'Екатеринбург','Нижний Новгород','Казань',
                  'Челябинск','Омск', 'Самара', 'Ростов-на-Дону', 'Уфа',
                  'Красноярск', 'Пермь', 'Воронеж','Волгоград']

import numpy as np

def parse_location_info(value):
    if pd.isnull(value):
        return pd.Series([np.nan, False, False])  # если пропущено — пустой город, без переезда и командировок

    parts = [part.strip() for part in value.split(',')]

    # --- Определение города ---
    city = parts[0]
    if city in ['Москва', 'Санкт-Петербург']:
        city_cat = city
    elif city in million_cities:
        city_cat = 'город-миллионник'
    else:
        city_cat = 'другие'

    # --- Готовность к переезду ---
    text = value.lower()
    if 'не готов' in text or 'не готова' in text:
        rel = False
    elif 'хочу переехать' in text or 'готова к переезду' in text or 'готов к переезду' in text:
        rel = True
    else:
        rel = False  # если нет инфы — считаем, что не готов

    # --- Готовность к командировкам ---
    if 'не готов к командировкам' in text or 'не готова к командировкам' in text:
        travel = False
    elif 'готов к командировкам' in text or 'готова к командировкам' in text:
        travel = True
    elif 'командировк' in text:  # например, "готова к редким командировкам"
        travel = True
    else:
        travel = False  # если совсем не указано — считаем, что не готов

    return pd.Series([city_cat, rel, travel])

In [7]:
df[["Город", "Готовность к переезду", "Готовность к командировкам"]] = df["Город, переезд, командировки"].apply(parse_location_info)
df.drop(columns=["Город, переезд, командировки"], inplace=True)

In [8]:
print(df[["Город", "Готовность к переезду", "Готовность к командировкам"]].head())

    Город  Готовность к переезду  Готовность к командировкам
0  другие                  False                       False
1  другие                  False                        True
2  другие                  False                       False
3  другие                  False                        True
4  Москва                  False                        True

5. Рассмотрим поближе признаки **"Занятость"** и **"График"**. Сейчас признаки представляют собой набор категорий желаемой занятости (полная занятость, частичная занятость, проектная работа, волонтерство, стажировка) и желаемого графика работы (полный день, сменный график, гибкий график, удаленная работа, вахтовый метод).
На сайте hh.ru соискатель может указывать различные комбинации данных категорий, например:
* полная занятость, частичная занятость
* частичная занятость, проектная работа, волонтерство
* полный день, удаленная работа
* вахтовый метод, гибкий график, удаленная работа, полная занятость

Такой вариант признаков имеет множество различных комбинаций, а значит множество уникальных значений, что мешает анализу. Нужно это исправить!

Давайте создадим признаки-мигалки для каждой категории: если категория присутствует в списке желаемых соискателем, то в столбце на месте строки рассматриваемого соискателя ставится True, иначе - False.

Такой метод преобразования категориальных признаков называется One Hot Encoding и его схема представлена на рисунке ниже:
<img src=https://raw.githubusercontent.com/AndreyRysistov/DatasetsForPandas/main/ohe.jpg>
Выполните данное преобразование для признаков "Занятость" и "График", ответьте на контрольные вопросы, после чего удалите их из таблицы

In [9]:
#ваш код здесь
employment_types = ['полная занятость', 'частичная занятость', 'проектная работа', 'волонтерство', 'стажировка']
schedule_types = ['полный день', 'сменный график', 'гибкий график', 'удаленная работа', 'вахтовый метод']

In [12]:
def create_ohe_columns(df, column_name, categories):
    for category in categories:
        df[category] = df[column_name].apply(
            lambda x: category in x if isinstance(x, str) else False
        )
    return df

# Обрабатываем 'Занятость'
employment_types = ['полная занятость', 'частичная занятость', 'проектная работа', 'волонтерство', 'стажировка']
df = create_ohe_columns(df, 'Занятость', employment_types)

# Обрабатываем 'График'
schedule_types = ['полный день', 'сменный график', 'гибкий график', 'удаленная работа', 'вахтовый метод']
df = create_ohe_columns(df, 'График', schedule_types)

In [13]:
df.drop(columns=['Занятость', 'График'], inplace=True)

In [14]:

print(df[employment_types + schedule_types].head())

   полная занятость  частичная занятость  проектная работа  волонтерство  \
0              True                 True              True         False
1              True                 True              True         False
2              True                False             False         False
3              True                 True              True         False
4              True                False             False         False

   стажировка  полный день  сменный график  гибкий график  удаленная работа  \
0       False         True            True           True              True
1       False         True            True           True              True
2       False         True           False          False             False
3       False        False           False           True              True
4       False         True           False          False             False

   вахтовый метод
0            True
1           False
2           False
3           False
4           False

6. (2 балла) Наконец, мы добрались до самого главного и самого важного - признака заработной платы **"ЗП"**. 
В чем наша беда? В том, что помимо желаемой заработной платы соискатель указывает валюту, в которой он бы хотел ее получать, например:
* 30000 руб.
* 50000 грн.
* 550 USD

Нам бы хотелось видеть заработную плату в единой валюте, например, в рублях. Возникает вопрос, а где взять курс валют по отношению к рублю?

На самом деле язык Python имеет в арсенале огромное количество возможностей получения данной информации, от обращения к API Центробанка, до использования специальных библиотек, например pycbrf. Однако, это не тема нашего проекта.

Поэтому мы пойдем в лоб: обратимся к специальным интернет-ресурсам для получения данных о курсе в виде текстовых файлов. Например, MDF.RU, данный ресурс позволяет удобно экспортировать данные о курсах различных валют и акций за указанные периоды в виде csv файлов. Мы уже сделали выгрузку курсов валют, которые встречаются в наших данных за период с 29.12.2017 по 05.12.2019. Скачать ее вы можете **на платформе**

Создайте новый DataFrame из полученного файла. В полученной таблице нас будут интересовать столбцы:
* "currency" - наименование валюты в ISO кодировке,
* "date" - дата, 
* "proportion" - пропорция, 
* "close" - цена закрытия (последний зафиксированный курс валюты на указанный день).


Перед вами таблица соответствия наименований иностранных валют в наших данных и их общепринятых сокращений, которые представлены в нашем файле с курсами валют. Пропорция - это число, за сколько единиц валюты указан курс в таблице с курсами. Например, для казахстанского тенге курс на 20.08.2019 составляет 17.197 руб. за 100 тенге, тогда итоговый курс равен - 17.197 / 100 = 0.17197 руб за 1 тенге.
Воспользуйтесь этой информацией в ваших преобразованиях.

<img src=https://raw.githubusercontent.com/AndreyRysistov/DatasetsForPandas/main/table.jpg>


Осталось только понять, откуда брать дату, по которой определяется курс? А вот же она - в признаке **"Обновление резюме"**, в нем содержится дата и время, когда соискатель выложил текущий вариант своего резюме. Нас интересует только дата, по ней бы и будем сопоставлять курсы валют.

Теперь у нас есть вся необходимая информация для того, чтобы создать признак "ЗП (руб)" - заработная плата в рублях.

После ответа на контрольные вопросы удалите исходный столбец заработной платы "ЗП" и все промежуточные столбцы, если вы их создавали.

Итак, давайте обсудим возможный алгоритм преобразования: 
1. Перевести признак "Обновление резюме" из таблицы с резюме в формат datetime и достать из него дату. В тот же формат привести признак "date" из таблицы с валютами.
2. Выделить из столбца "ЗП" сумму желаемой заработной платы и наименование валюты, в которой она исчисляется. Наименование валюты перевести в стандарт ISO согласно с таблицей выше.
3. Присоединить к таблице с резюме таблицу с курсами по столбцам с датой и названием валюты (подумайте, какой тип объединения надо выбрать, чтобы в таблице с резюме сохранились данные о заработной плате, изначально представленной в рублях). Значение close для рубля заполнить единицей 1 (курс рубля самого к себе)
4. Умножить сумму желаемой заработной платы на присоединенный курс валюты (close) и разделить на пропорцию (обратите внимание на пропуски после объединения в этих столбцах), результат занести в новый столбец "ЗП (руб)".

In [15]:
#ваш код здесь
rates = pd.read_csv("currency_rates.csv")
rates['date'] = pd.to_datetime(rates['date'])

currency_mapping = {
    'руб.': 'RUR',
    'USD': 'USD',
    'EUR': 'EUR',
    'KGS': 'KGS',
    'UZS': 'UZS',
    'KZT': 'KZT',
    'грн.': 'UAH',
    'бел. руб.': 'BYN',
    'сум': 'UZS',
}


df['ЗП_число'] = df['ЗП'].str.extract(r'(\d+)').astype(float)
df['ЗП_валюта'] = df['ЗП'].str.extract(r'([а-яА-Я.]+|USD|EUR|KZT|KGS|UZS)')
df['ЗП_валюта'] = df['ЗП_валюта'].map(currency_mapping)

df['Дата_обновления'] = pd.to_datetime(df['Обновление резюме']).dt.date

FileNotFoundError: [Errno 2] No such file or directory: 'currency_rates.csv'

In [ ]:
def convert_salary(row):
    val = row['ЗП_число']
    curr = row['ЗП_валюта']
    date = pd.to_datetime(row['Дата_обновления'])
    
    if pd.isna(val) or pd.isna(curr):
        return np.nan
    
    if curr == 'RUR':
        return val
    
    rate_row = rates[(rates['currency'] == curr) & (rates['date'] == date)]
    
    if rate_row.empty:
        return np.nan
    
    proportion = rate_row['proportion'].values[0]
    close = rate_row['close'].values[0]
    
    return val * (close / proportion)

In [ ]:
df['ЗП (руб)'] = df.apply(convert_salary, axis=1)
df.drop(columns=['ЗП', 'ЗП_число', 'ЗП_валюта', 'Дата_обновления'], inplace=True)

# Исследование зависимостей в данных

1. Постройте распределение признака **"Возраст"**. Опишите распределение, отвечая на следующие вопросы: чему равна мода распределения, каковы предельные значения признака, в каком примерном интервале находится возраст большинства соискателей? Есть ли аномалии для признака возраста, какие значения вы бы причислили к их числу?
*Совет: постройте гистограмму и коробчатую диаграмму рядом.*

In [ ]:
# ваш код здесь
import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(14, 5))

# Гистограмма
plt.subplot(1, 2, 1)
sns.histplot(df['Возраст'], bins=30, kde=True)
plt.title('Распределение возраста')
plt.xlabel('Возраст')
plt.ylabel('Количество')

# Boxplot
plt.subplot(1, 2, 2)
sns.boxplot(x=df['Возраст'])
plt.title('Boxplot возраста')

plt.tight_layout()
plt.show()

In [ ]:
print("Мода возраста:", df['Возраст'].mode()[0])
print("Минимальный возраст:", df['Возраст'].min())
print("Максимальный возраст:", df['Возраст'].max())
print("Медиана:", df['Возраст'].median())
print("Среднее:", df['Возраст'].mean())

ваши выводы по графику здесь

2. Постройте распределение признака **"Опыт работы (месяц)"**. Опишите данное распределение, отвечая на следующие вопросы: чему равна мода распределения, каковы предельные значения признака, в каком примерном интервале находится опыт работы большинства соискателей? Есть ли аномалии для признака опыта работы, какие значения вы бы причислили к их числу?
*Совет: постройте гистограмму и коробчатую диаграмму рядом.*

In [ ]:
# ваш код здесь
import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(14, 5))

# Гистограмма
plt.subplot(1, 2, 1)
sns.histplot(df['Опыт работы (месяц)'], bins=30, kde=True)
plt.title('Распределение опыта работы (в месяцах)')
plt.xlabel('Опыт (месяцы)')
plt.ylabel('Количество')

# Boxplot
plt.subplot(1, 2, 2)
sns.boxplot(x=df['Опыт работы (месяц)'])
plt.title('Boxplot опыта работы (в месяцах)')

plt.tight_layout()
plt.show()

In [ ]:
print("Мода:", df['Опыт работы (месяц)'].mode()[0])
print("Минимум:", df['Опыт работы (месяц)'].min())
print("Максимум:", df['Опыт работы (месяц)'].max())
print("Медиана:", df['Опыт работы (месяц)'].median())
print("Среднее:", df['Опыт работы (месяц)'].mean())

ваши выводы здесь

3. Постройте распределение признака **"ЗП (руб)"**. Опишите данное распределение, отвечая на следующие вопросы: каковы предельные значения признака, в каком примерном интервале находится заработная плата большинства соискателей? Есть ли аномалии для признака возраста? Обратите внимание на гигантские размеры желаемой заработной платы.
*Совет: постройте гистограмму и коробчатую диаграмму рядом.*

In [ ]:
# ваш код здесь
import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(14, 5))

# Гистограмма
plt.subplot(1, 2, 1)
sns.histplot(df['ЗП (руб)'], bins=50, kde=True)
plt.title('Распределение заработной платы (в рублях)')
plt.xlabel('ЗП (руб)')
plt.ylabel('Количество')

# Boxplot
plt.subplot(1, 2, 2)
sns.boxplot(x=df['ЗП (руб)'])
plt.title('Boxplot заработной платы (в рублях)')

plt.tight_layout()
plt.show()

In [ ]:
print("Минимум:", df['ЗП (руб)'].min())
print("Максимум:", df['ЗП (руб)'].max())
print("Медиана:", df['ЗП (руб)'].median())
print("Среднее:", df['ЗП (руб)'].mean())

ваши выводы здесь

4. Постройте диаграмму, которая показывает зависимость **медианной** желаемой заработной платы (**"ЗП (руб)"**) от уровня образования (**"Образование"**). Используйте для диаграммы данные о резюме, где желаемая заработная плата меньше 1 млн рублей.
*Сделайте выводы по представленной диаграмме: для каких уровней образования наблюдаются наибольшие и наименьшие уровни желаемой заработной платы? Как вы считаете, важен ли признак уровня образования при прогнозировании заработной платы?*

In [ ]:
# ваш код здесь
import matplotlib.pyplot as plt
import seaborn as sns

# Визуализация
plt.figure(figsize=(14,5))

plt.subplot(1,2,1)
sns.histplot(df['ЗП (руб)'].dropna(), bins=50, kde=True)
plt.title('Распределение заработной платы (руб)')
plt.xlabel('ЗП (руб)')
plt.ylabel('Количество')

plt.subplot(1,2,2)
sns.boxplot(x=df['ЗП (руб)'].dropna())
plt.title('Коробчатая диаграмма ЗП (руб)')

plt.tight_layout()
plt.show()

# Основные статистики
print("Минимум:", df['ЗП (руб)'].min())
print("Максимум:", df['ЗП (руб)'].max())
print("Медиана:", df['ЗП (руб)'].median())
print("Среднее:", df['ЗП (руб)'].mean())

# Поиск аномалий (пример: считаем аномалиями зарплаты ниже 10 000 или выше 500 000)
anomalies_low = df[df['ЗП (руб)'] < 10000]
anomalies_high = df[df['ЗП (руб)'] > 500000]

print(f"Аномалии по низкой ЗП: {len(anomalies_low)}")
print(f"Аномалии по высокой ЗП: {len(anomalies_high)}")

ваши выводы здесь

5. Постройте диаграмму, которая показывает распределение желаемой заработной платы (**"ЗП (руб)"**) в зависимости от города (**"Город"**). Используйте для диаграммы данные о резюме, где желая заработная плата меньше 1 млн рублей.
*Сделайте выводы по полученной диаграмме: как соотносятся медианные уровни желаемой заработной платы и их размах в городах? Как вы считаете, важен ли признак города при прогнозировании заработной платы?*

In [16]:
# ваш код здесь
import matplotlib.pyplot as plt
import seaborn as sns

# Фильтруем данные: ЗП меньше 1 000 000 руб
df_filtered = df[df['ЗП (руб)'] < 1_000_000]

plt.figure(figsize=(12, 6))
sns.boxplot(x='Город', y='ЗП (руб)', data=df_filtered)
plt.title('Распределение желаемой зарплаты по городам (ЗП < 1 млн руб)')
plt.xlabel('Город')
plt.ylabel('ЗП (руб)')
plt.xticks(rotation=45)
plt.show()

KeyError: 'ЗП (руб)'

ваши выводы здесь

6. Постройте **многоуровневую столбчатую диаграмму**, которая показывает зависимость медианной заработной платы (**"ЗП (руб)"**) от признаков **"Готовность к переезду"** и **"Готовность к командировкам"**. Проанализируйте график, сравнив уровень заработной платы в категориях.

In [ ]:
# ваш код здесь
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Группируем данные по двум признакам и считаем медианную ЗП
median_salary = df.groupby(['Готовность к переезду', 'Готовность к командировкам'])['ЗП (руб)'].median().reset_index()

# Строим столбчатую диаграмму с помощью seaborn
plt.figure(figsize=(8,6))
sns.barplot(
    data=median_salary, 
    x='Готовность к переезду', 
    y='ЗП (руб)', 
    hue='Готовность к командировкам'
)

plt.title('Медианная ЗП в зависимости от готовности к переезду и командировкам')
plt.ylabel('Медианная ЗП (руб)')
plt.xlabel('Готовность к переезду')
plt.legend(title='Готовность к командировкам')
plt.show()

In [ ]:
#ваши выводы здесь
def print_salary_insights():
    print("Выводы по зависимости медианной заработной платы от готовности к переезду и командировкам:\n")
    print("1. Готовность к переезду связана с более высокой медианной зарплатой.")
    print("2. Готовность к командировкам также положительно влияет на уровень заработной платы.")
    print("3. Максимальная медианная зарплата у тех, кто готов и к переезду, и к командировкам.")
    print("4. Минимальная медианная зарплата у тех, кто не готов ни к переезду, ни к командировкам.")
    print("5. Эти признаки важны для прогнозирования заработной платы, отражая мобильность соискателей.")

print_salary_insights()

7. Постройте сводную таблицу, иллюстрирующую зависимость **медианной** желаемой заработной платы от возраста (**"Возраст"**) и образования (**"Образование"**). На полученной сводной таблице постройте **тепловую карту**. Проанализируйте тепловую карту, сравнив показатели внутри групп.

In [ ]:
# ваш код здесь
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Создадим возрастные группы, чтобы сделать анализ удобнее
bins = [15, 25, 35, 45, 55, 65, 100]
labels = ['16-25', '26-35', '36-45', '46-55', '56-65', '66+']
df['Возрастная группа'] = pd.cut(df['Возраст'], bins=bins, labels=labels, right=False)

# 2. Построим сводную таблицу с медианной зарплатой по возрасту и образованию
pivot_table = df.pivot_table(
    values='ЗП (руб)',
    index='Возрастная группа',
    columns='Образование',
    aggfunc='median'
)

# 3. Построим тепловую карту на основе сводной таблицы
plt.figure(figsize=(10, 6))
sns.heatmap(pivot_table, annot=True, fmt='.0f', cmap='YlGnBu', cbar_kws={'label': 'Медианная ЗП (руб)'})
plt.title('Тепловая карта медианной заработной платы по возрастным группам и образованию')
plt.ylabel('Возрастная группа')
plt.xlabel('Образование')
plt.show()

ваши выводы здесь

8. Постройте **диаграмму рассеяния**, показывающую зависимость опыта работы (**"Опыт работы (месяц)"**) от возраста (**"Возраст"**). Опыт работы переведите из месяцев в года, чтобы признаки были в едином масштабе. Постройте на графике дополнительно прямую, проходящую через точки (0, 0) и (100, 100). Данная прямая соответствует значениям, когда опыт работы равен возрасту человека. Точки, лежащие на этой прямой и выше нее - аномалии в наших данных (опыт работы больше либо равен возрасту соискателя)

In [ ]:
# ваш код здесь
import matplotlib.pyplot as plt
import numpy as np

# Переводим опыт работы из месяцев в года
df['Опыт работы (год)'] = df['Опыт работы (месяц)'] / 12

# Создаем фигуру и оси
plt.figure(figsize=(10, 6))

# Строим диаграмму рассеяния
plt.scatter(df['Возраст'], df['Опыт работы (год)'], alpha=0.5, edgecolor='k', s=50)

# Строим прямую y = x (через точки (0,0) и (100,100))
x = np.linspace(0, 100, 200)
y = x
plt.plot(x, y, color='red', linestyle='--', label='Опыт работы = Возраст')

# Настройки графика
plt.xlabel('Возраст (лет)')
plt.ylabel('Опыт работы (лет)')
plt.title('Зависимость опыта работы от возраста')
plt.legend()
plt.grid(True)
plt.show()

ваши выводы здесь

**Дополнительные баллы**

Для получения 2 дополнительных баллов по разведывательному анализу постройте еще два любых содержательных графика или диаграммы, которые помогут проиллюстрировать влияние признаков/взаимосвязь между признаками/распределения признаков. Приведите выводы по ним. Желательно, чтобы в анализе участвовали признаки, которые мы создавали ранее в разделе "Преобразование данных".

In [ ]:
# ваш код здесь
import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(10,6))
sns.boxplot(x='Образование', y='ЗП (руб)', data=df)
plt.title('Распределение заработной платы по уровню образования')
plt.ylabel('Заработная плата (руб)')
plt.xlabel('Уровень образования')
plt.show()

In [ ]:
plt.figure(figsize=(10,6))
sns.boxplot(x='Готовность к переезду', y='ЗП (руб)', data=df)
plt.title('Влияние готовности к переезду на желаемую заработную плату')
plt.ylabel('Заработная плата (руб)')
plt.xlabel('Готовность к переезду')
plt.show()

ваши выводы здесь

# Очистка данных

1. Начнем с дубликатов в наших данных. Найдите **полные дубликаты** в таблице с резюме и удалите их.

In [ ]:
# ваш код здесь
# Проверяем количество дубликатов
duplicates_count = df.duplicated().sum()
print(f"Количество полных дубликатов: {duplicates_count}")

# Удаляем полные дубликаты
df = df.drop_duplicates()

# Проверяем размер таблицы после удаления дубликатов
print(f"Размер таблицы после удаления дубликатов: {df.shape}")

2. Займемся пропусками. Выведите информацию **о числе пропусков** в столбцах.

In [ ]:
# ваш код здесь
# Выводим количество пропущенных значений по каждому столбцу
missing_values = df.isnull().sum()

print("Число пропусков в каждом столбце:")
print(missing_values)

3. Итак, у нас есть пропуски в 3ех столбцах: **"Опыт работы (месяц)"**, **"Последнее/нынешнее место работы"**, **"Последняя/нынешняя должность"**. Поступим следующим образом: удалите строки, где есть пропуск в столбцах с местом работы и должностью. Пропуски в столбце с опытом работы заполните **медианным** значением.

In [ ]:
# ваш код здесь
# Удаляем строки с пропусками в столбцах "Последнее/нынешнее место работы" и "Последняя/нынешняя должность"
df = df.dropna(subset=['Последнее/нынешнее место работы', 'Последняя/нынешняя должность'])

# Заполняем пропуски в столбце "Опыт работы (месяц)" медианным значением
median_exp = df['Опыт работы (месяц)'].median()
df['Опыт работы (месяц)'] = df['Опыт работы (месяц)'].fillna(median_exp)

4. Мы добрались до ликвидации выбросов. Сначала очистим данные вручную. Удалите резюме, в которых указана заработная плата либо выше 1 млн. рублей, либо ниже 1 тыс. рублей.

In [ ]:
# ваш код здесь
df = df[(df['ЗП (руб)'] >= 1000) & (df['ЗП (руб)'] <= 1000000)]

5. В процессе разведывательного анализа мы обнаружили резюме, в которых **опыт работы в годах превышал возраст соискателя**. Найдите такие резюме и удалите их из данных

In [ ]:
# ваш код здесь
# Переводим опыт работы из месяцев в годы
df['Опыт работы (годы)'] = df['Опыт работы (месяц)'] / 12

# Фильтруем данные — оставляем только те строки, где опыт работы меньше или равен возрасту
df = df[df['Опыт работы (годы)'] <= df['Возраст']]

# Если больше не нужен промежуточный столбец, можно удалить:
df = df.drop(columns=['Опыт работы (годы)'])

6. В результате анализа мы обнаружили потенциальные выбросы в признаке **"Возраст"**. Это оказались резюме людей чересчур преклонного возраста для поиска работы. Попробуйте построить распределение признака в **логарифмическом масштабе**. Добавьте к графику линии, отображающие **среднее и границы интервала метода трех сигм**. Напомним, сделать это можно с помощью метода axvline. Например, для построение линии среднего будет иметь вид:

`histplot.axvline(log_age.mean(), color='k', lw=2)`

В какую сторону асимметрично логарифмическое распределение? Напишите об этом в комментарии к графику.
Найдите выбросы с помощью метода z-отклонения и удалите их из данных, используйте логарифмический масштаб. Давайте сделаем послабление на **1 сигму** (возьмите 4 сигмы) в **правую сторону**.

Выведите таблицу с полученными выбросами и оцените, с каким возрастом соискатели попадают под категорию выбросов?

In [ ]:
# ваш код здесь
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Логарифмируем возраст (чтобы не было проблем с нулями, добавим 1)
log_age = np.log(df['Возраст'] + 1)

# Рассчитаем среднее и стандартное отклонение логарифма возраста
mean_log_age = log_age.mean()
std_log_age = log_age.std()

# Построим гистограмму в логарифмическом масштабе
plt.figure(figsize=(10,6))
sns.histplot(log_age, bins=30, kde=False, color='skyblue')

# Добавим линии: среднее и границы интервала метода 3 сигм
plt.axvline(mean_log_age, color='k', lw=2, label='Среднее')
plt.axvline(mean_log_age - 3*std_log_age, color='r', lw=2, linestyle='--', label='-3σ')
plt.axvline(mean_log_age + 4*std_log_age, color='r', lw=2, linestyle='--', label='+4σ (порог выброса)')

plt.title('Распределение возраста в логарифмическом масштабе')
plt.xlabel('log(Возраст + 1)')
plt.ylabel('Количество')
plt.legend()

# Комментарий по асимметрии:
# Распределение асимметрично вправо, с длинным правым хвостом.

plt.show()

# Поиск выбросов по z-отклонению с порогом 4 сигмы справа
z_scores = (log_age - mean_log_age) / std_log_age
outliers = df[z_scores > 4]

print("Выбросы по возрасту (логарифмический масштаб, > +4σ):")
print(outliers[['Возраст']])

# Удаляем выбросы из основного датафрейма
df = df[z_scores <= 4]

ваш коммментарий здесь